# Generated by Django 4.2.5 on 2023-09-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='id',
            field=models.PositiveIntegerField(default=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='menu',
            name='inventory',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
